namespace EpsonFiscalInterface.Interop
{
    public enum AFIP_CODIGO_FORMA_DE_PAGO
    {
        CARTA_DE_CREDITO_DOCUMENTARIO = 1,
        CARTAS_DE_CREDITO_SIMPLE = 2,
        CHEQUE = 3,
        CHEQUES_CANCELATORIOS = 4,
        CREDITO_DOCUMENTARIO = 5,
        CUENTA_CORRIENTE = 6,
        DEPOSITO = 7,
        EFECTIVO = 8,
        ENDOSO_DE_CHEQUE = 9,
        FACTURA_DE_CREDITO = 10,
        GARANTIAS_BANCARIAS = 11,
        GIROS = 12,
        LETRAS_DE_CAMBIO = 13,
        MEDIOS_DE_PAGO_DE_COMERCIO_EXTERIOR = 14,
        ORDEN_DE_PAGO_DOCUMENTARIA = 15,
        ORDEN_DE_PAGO_SIMPLE = 16,
        PAGO_CONTRA_REEMBOLSO = 17,
        REMESA_DOCUMENTARIA = 18,
        REMESA_SIMPLE = 19,
        TARJETA_DE_CREDITO = 20,
        TARJETA_DE_DEBITO = 21,
        TICKET = 22,
        TRANSFERENCIA_BANCARIA = 23,
        TRANSFERENCIA_NO_BANCARIA = 24,
        OTROS_MEDIOS = 99,
    }
}
